########################################################################
#...Prompt that generated this program:
"""
Code is from an interactive session;
prompt still under development.
"""

########################################################################
#...Pseudocode for this program:
"""
# Parse command-line arguments
DEFINE parser AS ArgumentParser()
ADD argument "stats_file" (filename for training statistics)
ADD argument "model_file" (filename for saving trained classifier)
PARSE arguments

# Load extracted feature dataset from STDIN
SET feature_df = READ_CSV(STDIN, separator="\t")

# Extract feature columns and labels
SET X = feature_df EXCLUDING columns ["sampleID", "label"]
SET y = feature_df["label"]

# Split dataset into training (80%) and testing (20%) sets
SET (X_train, X_test, y_train, y_test) = TRAIN_TEST_SPLIT(X, y, test_size=0.20, stratify=y, random_seed=42)

# Initialize Random Forest Classifier
SET clf = RANDOM_FOREST(n_estimators=100, class_weight="balanced", random_seed=42)

# Perform 5-fold cross-validation on training set
SET cv_scores = CROSS_VAL_SCORE(clf, X_train, y_train, cv=5, scoring="roc_auc")

# Train classifier on full training set
TRAIN clf WITH (X_train, y_train)

# Evaluate model performance on test set
SET y_pred = PREDICT clf WITH X_test
SET test_accuracy = ACCURACY_SCORE(y_test, y_pred)
SET test_auc = ROC_AUC_SCORE(y_test, PREDICT_PROBA clf WITH X_test)

# Save training statistics to file
OPEN args.stats_file AS FILE f
    WRITE f "Cross-Validation AUC: MEAN(cv_scores) ± STD(cv_scores)"
    WRITE f "Test Accuracy: test_accuracy"
    WRITE f "Test AUC-ROC: test_auc"
CLOSE FILE f

# Save trained classifier model as a pickle file
OPEN args.model_file AS FILE f (WRITE_BINARY_MODE)
    SERIALIZE clf INTO f
CLOSE FILE f

# Print completion messages
PRINT "Training statistics saved to args.stats_file"
PRINT "Model saved to args.model_file"
"""

########################################################################
#...Code generated by Grimoire:
import sys
import argparse
import pandas as pd
import numpy as np
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score

# Parse command-line arguments
parser = argparse.ArgumentParser(description="Train a classifier and save the model with training statistics.")
parser.add_argument("stats_file", type=str, help="Filename to save training statistics.")
parser.add_argument("model_file", type=str, help="Filename to save the trained model as a pickle file.")
args = parser.parse_args()

# Print progress message to STDERR
sys.stderr.write("Loading extracted features from STDIN...\n")
sys.stderr.flush()

# Load extracted feature dataset from STDIN
feature_df = pd.read_csv(sys.stdin, sep="\t")

sys.stderr.write(f"Dataset loaded with {len(feature_df)} samples.\n")
sys.stderr.flush()

# Extract feature columns and labels
X = feature_df.drop(columns=["sampleID", "label"])  # Features
y = feature_df["label"]  # Labels (1 = disease, 0 = control)

sys.stderr.write("Splitting dataset into training (80%) and testing (20%)...\n")
sys.stderr.flush()

# Split into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

sys.stderr.write("Initializing Random Forest Classifier...\n")
sys.stderr.flush()

# Initialize Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight="balanced")

sys.stderr.write("Performing 5-fold cross-validation...\n")
sys.stderr.flush()

# Perform cross-validation (5-fold)
cv_scores = cross_val_score(clf, X_train, y_train, cv=5, scoring="roc_auc")

sys.stderr.write(f"Cross-validation completed. Mean AUC: {np.mean(cv_scores):.4f}\n")
sys.stderr.flush()

sys.stderr.write("Training classifier on full training set...\n")
sys.stderr.flush()

# Train final model on full training set
clf.fit(X_train, y_train)

sys.stderr.write("Training completed. Evaluating on test set...\n")
sys.stderr.flush()

# Evaluate on test set
y_pred = clf.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
test_auc = roc_auc_score(y_test, clf.predict_proba(X_test)[:, 1])

sys.stderr.write(f"Test Accuracy: {test_accuracy:.4f}, Test AUC-ROC: {test_auc:.4f}\n")
sys.stderr.flush()

sys.stderr.write(f"Saving training statistics to {args.stats_file}...\n")
sys.stderr.flush()

# Save training statistics
with open(args.stats_file, "w") as f:
    f.write(f"Cross-Validation AUC: {np.mean(cv_scores):.4f} ± {np.std(cv_scores):.4f}\n")
    f.write(f"Test Accuracy: {test_accuracy:.4f}\n")
    f.write(f"Test AUC-ROC: {test_auc:.4f}\n")

sys.stderr.write(f"Saving trained classifier to {args.model_file}...\n")
sys.stderr.flush()

# Save trained classifier model to a pickle file
with open(args.model_file, "wb") as f:
    pickle.dump(clf, f)

sys.stderr.write("Training complete! Model and statistics saved successfully.\n")
sys.stderr.flush()
