########################################################################
#...Prompt that generated this program:
"""

"""

########################################################################
#...Pseudocode for this program:
"""
BEGIN create_xmatrix_feature_set

    INPUT: input_file, output_file

    OPEN input_file FOR reading
    READ genome_ids FROM input_file
    CLOSE input_file

    DEFINE columns AS ["Sample"] + genome_ids + ["Disease Label"]

    OPEN output_file FOR writing
    WRITE columns TO output_file, separated by tabs
    CLOSE output_file

END create_xmatrix_feature_set

BEGIN main

    DEFINE input_file AS 'Data/rep10.list.tbl'
    DEFINE output_file AS 'Data/xmatrix.tsv'

    CALL create_xmatrix_feature_set(input_file, output_file)

END main


"""

########################################################################
#...Code generated by Grimoire:

# xmatrix_feature_set.py

def create_xmatrix_feature_set(input_file, output_file):
    # Open the input file and read the genome IDs
    with open(input_file, 'r') as infile:
        genome_ids = [line.strip() for line in infile]

    # Define the columns for the xmatrix
    columns = ["Sample"] + genome_ids + ["Disease Label"]

    # Open the output file and write the columns
    with open(output_file, 'w') as outfile:
        outfile.write("\t".join(columns) + "\n")

if __name__ == "__main__":
    # Define the input and output file paths
    input_file = 'Data/rep10.list.tbl'
    output_file = 'Data/xmatrix.tsv'

    # Create the xmatrix feature set
    create_xmatrix_feature_set(input_file, output_file)